#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
from __future__ import annotations

class FileSystemEventHandler: ...
class FileSystemEvent: ...
class DirModifiedEvent(FileSystemEvent): ...
class FileModifiedEvent(FileSystemEvent): ...
