class FileSystemEventHandler:
    def on_created(self, event: DirCreatedEvent | FileCreatedEvent) -> None: ...

class FileSystemEvent: ...
class FileCreatedEvent(FileSystemEvent): ...
class DirCreatedEvent(FileSystemEvent): ...
